### ISSUE TITLE
SQL server

### ISSUE THREAD

**Issue by fabio-rcs** [fabio-rcs/CYCLOGARD#4]
The SQL server needs to be created to store the information about the event: time, date, location and license plate of the vehicle.

**Comment by Yashar8991** [comment]
CREATE TABLE Event (
    EventID INT PRIMARY KEY IDENTITY,
    EventDate DATE NOT NULL,
    EventTime TIME NOT NULL,
    Location VARCHAR(50) NOT NULL,
    LicensePlate VARCHAR(20) NOT NULL
);

**Comment by fabio-rcs** [comment]
SQL server was cretated on the [FreeSQL](https://www.freesqldatabase.com/account/) site and is up and running with the name `sql7628878`.
![image](https://github.com/fabio-rcs/CYCLOGARD/assets/113982087/637caebe-37fa-4b25-92df-96f1fae6dd2a)
